[database]
DB_HOST = "funnywol_DB"
DB_USER = "root"
DB_PASSWORD = "Start123#"
DB_DATABASE = "wolserver"
DB_PORT = 3306

[proxmox]
NODENAME =  "pve"
PROX_HOST = "192.168.178.224"
PROX_TOKEN = "root@pam!anotherotherone"
PROX_SECRET = "238c1131-ceb6-4bc6-9f90-1e558cf6cdb4"
MAC = "6C:AE:8B:36:5F:A2"

[proxrm_server]
HOST = "0.0.0.0"
PORT = 3580

[logging]
LOGFILE = "XXX.log"
LOGLEVEL = "DEBUG"
